name: "Lychee Broken Link Checker"
description: "Quickly check links in Markdown, HTML, and text files"
inputs:
  args:
    description: "lychee arguments"
    default: "--verbose --no-progress './**/*.md' './**/*.html'"
    required: false
  format:
    description: "Summary output format (e.g. json)"
    default: "markdown"
    required: false
  output:
    description: "Summary output file path"
    default: "summary.md"
    required: false
  fail:
    description: "Fail entire pipeline on error (i.e. when lychee exit code is not 0)"
    default: false
    required: false
  jobSummary:
    description: "Write Github job summary at the end of the job (written on Markdown output only)"
    default: true
    required: false
  lycheeVersion:
    description: "Use custom version of lychee link checker"
    default: 0.10.0
    required: false
  createIssue:
    description: "Create Github issue if link check fails"
    default: true
    required: false
  issueTitle:
    description: "Title of Github issue which will be created if link check fails"
    default: Link Checker Report
    required: false
  issueLabels:
    description: "Attach labels to Github issue"
    default: links, report, automated issue
    required: false
  issueRepository:
    description: 'The target GitHub repository for creating issues'
    default: ${{ github.repository }}
  issueNumber:
    description: 'The issue number of an existing issue to update'

runs:
  using: "composite"
  steps:
    - run: |
        curl -LO 'https://github.com/lycheeverse/lychee/releases/download/v${{ inputs.LYCHEEVERSION }}/lychee-v${{ inputs.LYCHEEVERSION }}-x86_64-unknown-linux-gnu.tar.gz'
        tar -xvzf lychee-v${{ inputs.LYCHEEVERSION }}-x86_64-unknown-linux-gnu.tar.gz
        chmod 755 lychee
        mv lychee /usr/local/bin/lychee
      shell: bash

    - id: lychee
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        #https://github.com/actions/runner/issues/665
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_ARGS: ${{ inputs.ARGS }}
        INPUT_FORMAT: ${{ inputs.FORMAT }}
        INPUT_OUTPUT: ${{ inputs.OUTPUT }}
        INPUT_FAIL: ${{ inputs.FAIL }}
        INPUT_JOBSUMMARY: ${{ inputs.JOBSUMMARY }}
      shell: bash

    - if: inputs.CREATEISSUE && steps.lychee.outputs.exit_code != 0
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: ${{ inputs.ISSUETITLE }}
        labels: ${{ inputs.ISSUELABELS }}
        repository: ${{ inputs.ISSUEREPOSITORY }}
        issue-number: ${{ inputs.ISSUENUMBER }}
        content-filepath: ${{ inputs.OUTPUT }}

branding:
  icon: "external-link"
  color: "purple"
